{% set name = "pyzbar" %}
{% set version = "0.1.8" %}
{% set sha256 = "f51c82c2864f8e5a8d44f55853e027f8cbc592324b7afffa62100f2f9c54cbdb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NaturalHistoryMuseum/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<36]
  entry_points:
    - read_zbar = pyzbar.scripts.read_zbar:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.8.2
    - pillow >=3.2.0

test:
  requires:
    - pytest
  source_files:
    - pyzbar/tests/
  imports:
    - pyzbar
  commands:
    - pytest -v
    - read_zbar --help
    - read_zbar pyzbar/tests/code128.png
    - read_zbar pyzbar/tests/empty.png
    - read_zbar pyzbar/tests/qrcode.png
    - read_zbar pyzbar/tests/qrcode_rotated.png

about:
  home: https://github.com/NaturalHistoryMuseum/pyzbar
  license: MIT
  license_file: LICENSE.txt
  summary: Read one-dimensional barcodes and QR codes from Python 2 and 3.
